### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe (with billing service)",
  "email": "john.doe.billing.account@example.com",
  "address": "123 Main Street 22",
  "dateOfBirth": "1992-09-09",
  "registeredDate": "2024-11-28"
}
###